# Site settings
title: Advanced Robotic Lab
email: ckloo.um@um.edu.my
url: https://arl.fsktm.um.edu.my
description: "Advanced Robotic Lab (ARL) is focusing on advances of Robotics, Machine Learning, Artificial Intelligence, Information Technology, etc."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Advanced Robotic Lab
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: github
    url: http://github.com/arlab

# Postal address (add as many lines as necessary)
address:
  - line: Advanced Robotic Lab
  - line: Department of Artificial Intelligence
  - line: Faculty of Computer Science & IT
  - line: University of Malaya, Malaysia

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
